apiVersion: eventflow.dev/v1alpha1
kind: FilesystemReceiver
metadata:
  name: school-events-in
spec:
  path: ./var/school-events.ndjson
  format: ndjson
---
apiVersion: eventflow.dev/v1alpha1
kind: FilesystemEmitter
metadata:
  name: school-events-out
spec:
  path: ./var/school-events.validated.ndjson
  format: ndjson
---
apiVersion: eventflow.dev/v1alpha1
kind: EventContract
metadata:
  name: attendance-submitted
spec:
  type: attendance.submitted.v1
  payloadSchema: ./contracts/events/payloads/attendance-submitted.v1.schema.json
  requiredExtensions:
    - correlationid
---
apiVersion: eventflow.dev/v1alpha1
kind: EventContract
metadata:
  name: student-enrolled
spec:
  type: student.enrolled.v1
  payloadSchema: ./contracts/events/payloads/student-enrolled.v1.schema.json
---
apiVersion: eventflow.dev/v1alpha1
kind: EventFlow
metadata:
  name: school-file-flow
spec:
  receiverRef:
    kind: FilesystemReceiver
    name: school-events-in
  contractRefs:
    - kind: EventContract
      name: attendance-submitted
    - kind: EventContract
      name: student-enrolled
  emitterRefs:
    - kind: FilesystemEmitter
      name: school-events-out
