apiVersion: batch/v1
kind: Job
metadata:
  name: eventflow-validate
spec:
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
      containers:
        - name: eventflow
          image: ghcr.io/rezarajan/eventflow:latest
          args: ["validate", "--config", "/etc/eventflow/resources.yaml"]
          volumeMounts:
            - name: config
              mountPath: /etc/eventflow
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: eventflow-config
